# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: siemens/mosquitto-backend-controller-server
  tag: 0.0.0.1

imagePullPolicy: IfNotPresent

ingress:
  enabled: false
  
  
service:
  enabled: true
  type: "ClusterIP"
  port: 3366



persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
#  storageClass: standard
  annotations: {}
  
resources:
  requests:
    cpu: 50m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}

customResources:
  enablespecificdownload: false
