apiVersion: apps/v1
kind: Deployment
metadata:
  name: sim-edge-mosquitto-broker
  labels:
    app: {{ include "sim-edge-mosquitto-broker.name" . }}
    chart: {{ include "sim-edge-mosquitto-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.scale}}
  selector:
    matchLabels:
      app: {{ include "sim-edge-mosquitto-broker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "sim-edge-mosquitto-broker.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        name: {{ include "sim-edge-mosquitto-broker.name" . }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: "mqtt-port"
          {{- if not .Values.service.enabled }}
          hostPort: {{ .Values.service.hostPort }}
          {{- end }}
          protocol: TCP  
        resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.customResources.enablespecificdownload }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
